# general
epochs: 300
batch_size: 2
num_workers: 0
syncbn: False
mc: False
seed: 666
save_checkpoint: 20

# loss
criterions: [['ce', 1], ['encoder_patchseries', 0.1], ['decoder_patchseries', 0.01], ['multi_layer_patchseries', 0.01]]  
class_weight: [1, 1]  
loss_temperature: 1
      
model:
    mode: 'DeepLab_bcl_att2' 
    input_channel: 3
    num_classes: 2
    backbone: 'xception_bcl_att2'  
    output_stride: 16   
    freeze_bn: False 

    # our method
    layer_sample: [128, 64, 32, 8, 8, 8, 8, 8, 8, 8, 1, 8, 8, 8]
    loss_layerchoice: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

    distance_measure: 'cosine'
    fea_weight_choice: 'receptive_field'
    sample_strategy: 'stride'
    bcl_layer_choice: [2,3] 

    bcl_multi_layer_choice: [2,3] 
    layer_sample_multilayer: [32, 32, 32, 32, 32]

    instance_dis: False


    patchnumber: 3 
    patchsize: [5, 7, 9] 
    similarityfirst_encoder: True 
    similarityfirst_decoder: True 
    similarityfirst_multi: True 
    patchforeground_weight: [1.0, 1.0, 1.0]    

    uncertainty_att_layerchoice: [1,1,1,1,1,  0,0,0,0,0,  1,1] 


dataset:
    mode: 'ISIC2016'
    root_path: './data/'
    input_size: [384, 384, 3]
    preload: False
    aug: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    modality: '2D'

data_aug:
    affine:
      scale: [0.8, 1.2]
      translate: [0.1, 0.1]
      rotate: [-90, 90]
      shear: [-20, 20]
    flip: [0.5, 0.5]

optm:
    mode: 'adam'
    use_larc: False
    sgd:
        base_lr: 0.1
        final_lr: 0.00001
        momentum: 0.9
        wd: 0.00001
    adam:
        base_lr: 0.001
        final_lr: 0.00001
        wd: 0.00001
    larc: 
      trust_coefficient: 0.001
      clip: False

schd:
    mode: 'cos'
    step:
      milestone: [30, 50, 80]  # epoch
      decay_rate: 0.1
    exp:
      gamma: 0.97
    cos:
      start_warmup: 0
      warmup_epochs: 2

test:
  start_test_epoch: 130
  test_intertest: 1
  rank_metric: ['mIoU']  
  metric_used: ['mDice', 'mIoU', 'Acc']  
  resize_option: 'resize_first'  
  resize_interpolation: 'bilinear'  
        