# general
epochs: 200
batch_size: 8
num_workers: 4
syncbn: True
mc: False
seed: 666
save_checkpoint: 100

# loss
criterions: [['ce', 1], ['dice', 1]]  # check loss_utils.py for details
class_weight: [1, 1, 1, 1, 1]  # len(class_weight) should be equal to model.num_classes
loss_temperature: 1
      
model:
    mode: 'DeepLab_3d' 
    backbone: 'resnet'
    num_classes: 5
    output_stride: 16   # 16 or 8
    freeze_bn: False 

dataset:
    mode: 'Plaques'
    root_path: '/home/SENSETIME/lizhuowei/Desktop/tem/'
    input_size: [64, 64, 64]
    aug: True
    modality: '3D'

data_aug:
    affine:
      scale: [0.8, 1.2]
      translate: [0.1, 0.1]
      rotate: [-90, 90]
      shear: [-20, 20]
    flip: [0.5, 0.5]

optm:
    mode: 'adam'
    use_larc: False
    sgd:
        base_lr: 0.1
        final_lr: 0.00001
        momentum: 0.9
        wd: 0.00001
    adam:
        base_lr: 0.001
        final_lr: 0.00001
        wd: 0.00001
    larc: 
      trust_coefficient: 0.001
      clip: False

schd:
    mode: 'cos'
    step:
      milestone: [30, 50, 80]  # epoch
      decay_rate: 0.1
    exp:
      gamma: 0.97
    cos:
      start_warmup: 0
      warmup_epochs: 2

val:
  start_val_epoch: 0
  val_interval: 1
  rank_metric: ['mIoU']  # main metric used for ranking
  metric_used: ['Dice', 'IoU', 'fwIoU', 'Acc', 'Acc_class']  # 'mDice', 'mIoU', 'fwIoU', 'Acc', 'Acc_class'
  metric_mode: 'micro'  # 'macro or micro'
  resize_option: 'resize_first'  # 'resize_first', 'resize_after'
  resize_interpolation: 'trilinear'  # 'nearest', 'linear', 'bilinear', 'bicubic', 'trilinear', 'area'
        
